### ISSUE TITLE
searching similar molecules

### ISSUE THREAD

**Issue by abhik1368** [samoturk/mol2vec#1]
Hi Sam,

Is it possible to perform similarity search with the model ? Any ideas how could it be done ?

**Comment by sa-ja** [comment]
You could generate the vectors for a database (e.g. chembl). Then you calculate cosine distance between the vector of the molecule you are interested in and every molecule you want to compare it to. The compounds with lowest distance should be similar.

**Comment by samoturk** [comment]
Exactly, I would just add that calculating cosine (or any other) distance between vectors with floats (like mol2vec) is much slower compared to calculating Jaccard (Tanimoto) distance using binary vectors (like Morgan FPs).
