### ISSUE TITLE
blog: experiment using mol2vec

### ISSUE THREAD

**Issue by iamsabhoho** [samoturk/mol2vec#10]
Hi, 

I've done some similarity search experiments using your project mol2vec. Here is a draft of my blog. I'd appreciate if you could please read it and give me some feedback. Thank you!

draft link: https://medium.com/@sabrina.sj.ho/tanimoto-vs-mol2vec-7fa4af3208ef

**Comment by samoturk** [comment]
Hi Sabrina,

I really like your post! I only found 2 minor errors:

- the animation shows a plot where identifiers (substructures) are grouped based on their similarity and not molecules. Substructures are only shown on a representative molecule. 
- Check you spelling of ChEMBL

You can also use cdist to calculate pairwise distances:
```python
from scipy.spatial.distance import cdist

v1 = [0,0,0]
v2 = [0,0,1]
v3 = [0,0,2]

cdist([v2,v3], [v1], metric='euclidean')
```

Good luck with your blog and research!

**Comment by iamsabhoho** [comment]
Hi, 

Thanks for the suggestions! I finished my blog: https://medium.com/gsi-technology/tanimoto-vs-mol2vec-7fa4af3208ef
