### ISSUE TITLE
Transfer learning

### ISSUE THREAD

**Issue by nsantini** [samoturk/mol2vec#2]
Hi, first, thanks for making this great OSS library, much appreciated.

Im interested in taking the pretrained ZINC based model and further train it with sentences from my data set. The reason for this approach is that my dataset is small, only a few thousand SMILES. So Im trying to take a page from the CNN book where you can take a pretrained image recognition model and further specialized for your use case.

Is there any way to achieve that within your library?

**Comment by samoturk** [comment]
Thanks!

mol2vec uses word2vec implementation from Gensim and it doesn't seem to support this: https://radimrehurek.com/gensim/models/word2vec.html

**Comment by nsantini** [comment]
As it turns out you actually can. Here is what Ive done: after preparing the corpus with cli tool provided here.
```
from gensim.models import word2vec
corpus=[]
with open('corpus.cp', 'r') as f:
    for i, line in enumerate(f):
        corpus.append(line)
model = word2vec.Word2Vec.load('model_300dim.pkl')
model.train(corpus, total_examples=len(corpus), epochs=10)
model.save('updatedmodel.pkl')
```

**Comment by samoturk** [comment]
That's useful. Thanks for sharing!
