### ISSUE TITLE
Convert back Base64encoded string of ROMol into an object of <rdkit.Chem.rdchem.Mol>

### ISSUE THREAD

**Issue by directlinks** [samoturk/mol2vec#5]
I have a base64encoded string of ROMOL which needs to be converted back to it's original object form. I am using the base64encoded string to write the data into the text format, but after reading the text format I need to convert it back into it's object so that I can generate embeddings using the object via the function "mol2alt_sentence".

I am only able to save the base64encoded romol in string format instead of serialized object. Therefore, the functionality of converting the string back to the object is required. Please suggest any alternative solution for this issue.

**Comment by samoturk** [comment]
Hi @directlinks,
I'm not sure I understand your issue completely. Can you please give a code example?
