### ISSUE TITLE
Convert sentences to mol

### ISSUE THREAD

**Issue by cddt** [samoturk/mol2vec#8]
After applying `mol2alt_sentence` to get the molecular sentence, is there any way to convert this back to the Mol object? 

E.g. I have the sentence `['1016841875', '198706261', '2245384272', '2909042096', '2245384272', '2909042096', '1016841875', '198706261']` - can I convert this back to an `rdkit.Chem.rdchem.Mol` object? 

I have found the object `mol2vec.helpers.IdentifierTable` but I'm unsure what's used for or if its helpful. 

PS: the mol2vec project is a great implementation and very helpful for my research so far!

**Comment by samoturk** [comment]
After quickly thinking about it, I think it is potentially possible to reconstruct a molecule from Morgan identifiers but would probably be quite a hurdle to implement this and I also don't know of such implementation.

Thanks for using it! :)

**Comment by cddt** [comment]
I have an idea for an implementation. I will let you know if I can make any progress on it (probably not before November due to other commitments).
