### ISSUE TITLE
How Do You Convert RDKIT molecule to your fingerprint key ?

### ISSUE THREAD

**Issue by sourcesync** [samoturk/mol2vec#9]
Hi !

We are very excited about using your project.   We have the notebook samples working and we want to try on our own RDKIT molecules.

Unfortunately, we don't know how to convert RDKIT molecules into the morgan fingerprints that you are using as keys into the embedding dictionary.  We can convert RDKIT molecules to bit vectors, but can't seem to match RDKIT molecules into your non-bit-vector representation (integers?).

Please advise ! 

Thanks !

**Comment by sourcesync** [comment]
This RDKIT post seems relevant.  It seems other folks have problems converting the RDKIT bitvector into some other more compact number.  How are you doing it ?  Thanks again !

https://sourceforge.net/p/rdkit/mailman/message/24426410/

**Comment by samoturk** [comment]
I assume you are talking about Morgan identifiers (non-hashed fp). I'm using [GetMorganFingerprint](https://github.com/samoturk/mol2vec/blob/master/mol2vec/features.py#L150-L151) and extracting identifiers from `info`.
```python
info = {}
_ = AllChem.GetMorganFingerprint(mol, radius, bitInfo=info)
```
